#   This python program will produce three(3) random numbers just like a lottery.
#   If the user managed to guess the right numbers then he/she is considered a winner!
#   In this program, 'for', 'while', and 'if - else' loops has been used.

restart = True

while restart:
     
    import random
 
    ask_User = []

#STEP.1- The program will ask the user to enter 3 random numbers between 0-9
#        If the user tries to enter digit lower than the minimum or exceeding the maximum value, then the input will be invalid
    for i in range (0,3):
        num = int(input("Input random numbers between 0 to 9: "))
        while (num in ask_User or num < 0 or num > 9):
            print("The entered number is invalid! Please try again.")
            num = int(input("Input random numbers between 0 to 9: "))

        ask_User.append(num)

    Lottery_Num = []

#STEP.2- On this step, the program will now generate 3 random numbers between 0-9
    for i in range (0,3):
        num = random.randint(0, 9)
        while num in Lottery_Num:
            num = random.randint(0, 9)

        Lottery_Num.append(num)

#STEP.3- The inputted numbers by the user will be compared to the 3 random numbers generated by the program.
#        If the user guess are all correct, the program will print a short congratulatory message.
    print("Lottery result: ")
    print(Lottery_Num)

    print("Your 3 random numbers are: ")
    print(ask_User)

    if num in ask_User == Lottery_Num:
        print("Winner! Congratulations!\n")
    else:
        print("You Lose!\n")

#STEP.4- Lastly, the program will ask the user if he/she wants to restart the game again.
#        IF the user entered 'y', the program will start again but if the user entered 'n', the program will be dismissed.
    restart = input("Do you want to try again?\nPress [y] to restart or [n] to quit: ")
    if restart == "n":
        restart = False
    if restart == "y":
        restart = True
